In [48]:
n, m = map(int, input().split())
a = [[int(i) for i in input().split()] for _ in range(n)]
m, k = map(int, input().split())
b = [[int(i) for i in input().split()] for _ in range(m)]

3 2
1 2
3 4
5 6
2 3
-1 -2 0
0 0 3


In [60]:
# ans = [[0] * k] * n 왜 반복문으로 안하면 틀릴까
# print(ans)
ans = [[0 for _ in range(k)] for _ in range(n)]

for i in range(n):
    for j in range(k):
        for x in range(m):
            ans[i][j] += a[i][x] * b[x][j]

for i in range(n):
    print(*ans[i])

-1 -2 6
-3 -6 12
-5 -10 18


In [45]:
import numpy as np

print(np.dot(a,b))

[[ -1  -2   6]
 [ -3  -6  12]
 [ -5 -10  18]]
