행렬 제곱 골드 4

In [79]:
import numpy as np

n, b = map(int, input().split())
arr = np.empty((0, n), int)

for _ in range(n):
#     arr_ = (list(map(int, (input().split()))))
    arr_ = [int(x) for x in input().split()]
    arr = np.append(arr, np.array([arr_]), axis=0)
     
# b = bin(b)[2:]
x = int(bin(b)[2]) #0bxxxxxx
y = b - 2 ** x
mat = arr

for _ in range(x):
    mat = mat.dot(mat)
    
for _ in range(y):
    mat = mat.dot(arr)

for item in mat:
#     print(item % 1000)
    for i in item:
        print(i % 1000, end=' ')
    print()

3 3
1 2 3
4 5 6
7 8 9
468 576 684 
62 305 548 
656 34 412 


In [88]:
# for i in range(n):
#     for j in range(n):
#         if i == j:
#             res[i][j] = 1

def mat_mul(a, b, n):
    res = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            temp = 0
            for k in range(n):
                temp += a[i][k] * b[k][j]
            res[i][j] = temp
    return res

            
n, b = map(int, input().split())
arr = [[int(i) for i in input().split()] for _ in range(n)]

x = len(bin(b)[2:])-1 #0bxxxxxx
y = b - 2 ** x
mat = arr

for _ in range(x):
    mat = mat_mul(mat, mat, n)
    
for _ in range(y):
    mat = mat_mul(mat, arr, n)

for item in mat:
    for i in item:
        print(i % 1000, end=' ')
    print()

5 10
1 0 0 0 1
1 0 0 0 1
1 0 0 0 1
1 0 0 0 1
1 0 0 0 1
512 0 0 0 512 
512 0 0 0 512 
512 0 0 0 512 
512 0 0 0 512 
512 0 0 0 512 


In [85]:
z = [[1, 2], [3, 4]]
zm = np.array(z)

zm = zm.dot(zm)
print(zm)
zm = zm.dot(zm)
print(zm)
zm = zm.dot(z)
print(zm)

[[ 7 10]
 [15 22]]
[[199 290]
 [435 634]]
[[1069 1558]
 [2337 3406]]
